### PR TITLE
Autogenerate man page

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Review by bluca — APPROVED** [review]

**Comment by bluca** [comment]
```
make dlopen-notes.1
argparse-manpage 	\
	--output=dlopen-notes.1 	\
	--pyfile=dlopen-notes.py 	\
	--function=make_parser \
	--project-name=package-notes \
	--include=docs/dlopen-description.man
usage: argparse-manpage [-h] (--module MODULE | --pyfile PYFILE) (--function FUNCTION | --object OBJECT)
                        [--author AUTHOR] [--author-email AUTHOR_EMAIL] [--project-name NAME] [--url URL]
                        [--output OUTFILE]
argparse-manpage: error: unrecognized arguments: --include=docs/dlopen-description.man
make: *** [Makefile:4: dlopen-notes.1] Error 
```

**Comment by bluca** [comment]
Dropping that parameter I get:

```
argparse-manpage(1)                           General Commands Manual                           argparse-manpage(1)

NAME
       argparse-manpage

SYNOPSIS
       argparse-manpage [-r] [-s] [-f [FEATURE1,FEATURE2]] [-h] filename [filename ...]

DESCRIPTION
       Read .note.dlopen notes from ELF files and report the contents.

OPTIONS
       filename
              Library file to extract notes from

       -r, --raw
              Show the original JSON extracted from input files

       -s, --sonames
              List all sonames and their priorities, one soname per line

       -f [FEATURE1,FEATURE2], --features [FEATURE1,FEATURE2]
              Describe features, can be specified multiple times

AUTHORS
       package-notes was written by <<UNSET --author OPTION>> <<<UNSET --author_email OPTION>>>.

DISTRIBUTION
       The latest version of package-notes may be downloaded from ⟨<<UNSET⟩
```

**Comment by keszybz** [comment]
Hmm, maybe you have an old version of argparse-manpage? But the list at https://github.com/praiskup/argparse-manpage/ says Debian 12 has 4.5, same as here.

**Comment by bluca** [comment]
Nope, debian stable has 1.2.2 https://packages.debian.org/search?keywords=argparse-manpage&searchon=names&suite=all&section=all

**Comment by bluca** [comment]
Just generate it once with that tool and check the result in? I can't imagine we are going to change this that often...

**Comment by keszybz** [comment]
Whatever is easier. I think both options have merit ;)

**Pull request merged**
